[project]
name = "highjump-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noé Felber", email = "noe.felber@gmx.ch" }
]
requires-python = ">=3.13"
dependencies = [
    "google-cloud-storage>=3.1.0",
    "joblib>=1.5.3",
    "lxml>=6.1.0",
    "mlflow>=1.27.0",
    "pandas>=3.0.2",
    "protobuf>=5.29.0,<6",
    "pyarrow>=24.0.0",
    "requests>=2.33.1",
    "scikit-learn>=1.8.0",
    "setuptools<82",
    "streamlit>=1.57.0",
]

[project.scripts]
highjump-mlops = "highjump_mlops:main"
fetch-data = "highjump_mlops.data.collection:main"
feature-pipeline = "highjump_mlops.features.pipeline:main"
train-pipeline = "highjump_mlops.training.pipeline:main"
inference = "highjump_mlops.inference.cli:main"
upload-cloud-artifacts = "highjump_mlops.cloud.artifacts:upload_artifacts_cli"
download-cloud-artifacts = "highjump_mlops.cloud.artifacts:download_artifacts_cli"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
